version: '3.8'
services:
  backend:
    build: backend
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./app/node_modules
  db:
    image: mysql:9.3.0
  frontend:
    build: frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true