version: '3.8'
services:
  backend:
    build: backend
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./app/node_modules
  db:
    image: mysql:8.3
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bankdb
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  frontend:
    build: frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true